### ISSUE TITLE
Mount Minecraft Server Files

### ISSUE THREAD

**Issue by Shariner** [evilmarty/hassio-addons#100]
Hi,

maybe i am to stupid to use it, but how can I access the server files, for downloading world data, change op users etc?
You write "The share directories are mounted for your convenience." but there is no folder for minecraft in the share partition. Also not in config/addons.

Thanks

**Comment by evilmarty** [comment]
You can change the settings conveniently for the add-on and set any paths with `/share` to have them stored there.

**Comment by Shariner** [comment]
Hello @evilmarty ,
sorry, i still don't get it. Where can I set a path with /share? Of cause the command /share does not work on SSH. How can I see the server files like the world data?
