### ISSUE TITLE
Radarr fails to update again 

### ISSUE THREAD

**Issue by Puppetmaster91** [evilmarty/hassio-addons#109]
Hi

Radarr fails to update in HAOS

Can't install ghcr.io/evilmarty/hassio-radarr:5.3.6.8612-ls207: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=5.3.6.8612-ls207&fromImage=ghcr.io%2Fevilmarty%2Fhassio-radarr&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

You have 5.2.6.8376-ls202 installed. Click update to update to version 5.3.6.8612-ls207

**Comment by evilmarty** [comment]
Hi. I appreciate you taking the time to report the issue. It was caused by issues with the GitHub workflows not properly triggering to build the container. I've refactored them to hopefully not be an issue in the future.
