### ISSUE TITLE
Request bazarr

### ISSUE THREAD

**Issue by skank01** [evilmarty/hassio-addons#16]
Hi
No issue but a request. 
Using sonarr, radarr, sabnzb, but i'm missing bazarr.
Any chance you add that one too?

**Comment by evilmarty** [comment]
You're welcome to contribute but I have no need to run that application to warrant including it.

**Comment by skank01** [comment]
hi ok np, ill get it from somewhere else then :)

Op di 30 aug. 2022 om 10:20 schreef Marty Zalega ***@***.***>:
