### ISSUE TITLE
Sabnzb 

### ISSUE THREAD

**Issue by skank01** [evilmarty/hassio-addons#17]
Hi,

I installed your sabnzb and sonarr addon
EVerything good so far.
However when i try to add the download client into sonarr, it says its not available
I think something is wrong with ip:port

The webui of sonarr has its own ip of homeassistant, and the port 8989
Sabnzb though is unreachable when typing ip of home assistant and port 8080
However the ui is loaded into the home assistant ui , with the home assistant port 8123

How can i make sabnzb to be reachable with the ip and port 8080 so i can point to it in sonarr?

Thx!

**Comment by evilmarty** [comment]
You can do it by referencing the add-on's hostname. This is presented on the add-on's info page like so...

<img width="924" alt="Screen Shot 2022-08-30 at 7 56 01 am" src="https://user-images.githubusercontent.com/44270/187306107-471eb2eb-2ae8-43d2-8b37-ee8e2ff6e068.png">

You can then just use the standard port of 8989.

**Comment by evilmarty** [comment]
Are you also setting the API key? That needs to match what is set in .SABnzbd.

**Comment by skank01** [comment]
> Are you also setting the API key? That needs to match what is set in .SABnzbd.

Yes i copied the api key from sabnzb and put it in sonarr settings, but thats not the problem.
The problem is the ip i dont know what to put in.

Can you give me an example pls?
Normal port of sabnzb  is 8080

So how should the url look like? Cause using the ip of the home assistant device doesnt work

**Comment by skank01** [comment]
Maybe a screenshot of your settings.
You both have sab and sonarr or radarr running HA OS with the addon right? On same machine...

**Comment by skank01** [comment]
Using nzbget now without issue
