### ISSUE TITLE
sabnzbd not accessible for Chrome Addon

### ISSUE THREAD

**Issue by tuffelh** [evilmarty/hassio-addons#18]
Hi, 
I just installed the addon and everything is working so far ....except:
When I try to use a Chrome Addon like NZBDonkey (https://chrome.google.com/webstore/detail/nzbdonkey/edkhpdceeinkcacjdgebjehipmnbomce) - I cannot connect to the sabnzbd instance - I think this is related to ingress.
Even if I set the reverse Proxy pattern to "22xx2f96_sabnzbd/" I only get the error "405 - Method not allowed"

Is there any workaround?

**Comment by evilmarty** [comment]
I've reverted the ingress setup. You'll need to re-install the add-on but it should be accessible directly afterwards.
