### ISSUE TITLE
Lidarr addon not working on a Raspberry Pi 4B 64 bit

### ISSUE THREAD

**Issue by almico** [evilmarty/hassio-addons#3]
I tried to install your Lidarr addon and start it.

![image](https://user-images.githubusercontent.com/15247405/135762551-45b25253-8786-4a95-9299-3acfa8834a4a.png)

All I see is the following line in "Log":

`standard_init_linux.go:228: exec user process caused: exec format error`

And trying to open its web UI, I get a `connection refused` error.

**Comment by evilmarty** [comment]
That appears to be correct. You are using the AMD64 version instead of the ARM64 version. The reason is that the base image that's being used doesn't include both architectures and rather are separate images. It's on my list to combine these into a multi-arch image.

**Comment by evilmarty** [comment]
@almico I've updated the build workflow to build ARM64 and ARMv7 docker images. Can you please test with the latest version to see if that fixes the issue?
