### ISSUE TITLE
Radarr: Can't find/add TorrentLeech as Indexer

### ISSUE THREAD

**Issue by hulkhaugen** [evilmarty/hassio-addons#34]
When adding Indexers, TorrentLeech isn't in the list. However, using Sonarr, it shows up. From looking at online tutorials, it seems that there should be plenty of indexeres listed, but i only see 9 in each arr-app. Dunno i'f it could be cache related or where to find it, i just don't want to mess up my current settings. I installed both add-ons quite recently for the first time, maybe 2-3 months ago.

EDIT: I just noticed that you have updated the versions in config.yaml, but not in the Dockerfile, so I suppose it's not actually being updated.

**Comment by evilmarty** [comment]
Hi @hulkhaugen. I've fixed up the images and the update workflow so it will update the config version and docker file image tag to ensure they match. All images have been rebuilt with the latest corresponding version.
