### ISSUE TITLE
[Request] Overseerr and Prowlarr add-on

### ISSUE THREAD

**Issue by ikrowni** [evilmarty/hassio-addons#4]
Hello would it be possible for you to add the [overseerr](https://overseerr.dev/) and [Prowlarr](https://github.com/Prowlarr/Prowlarr/) addon.

These 2 addons would significantly increase the use of the others youve already added allowing many more providers to be added to the other services along with an easy to use request system for adding new titles to those services.

**Comment by evilmarty** [comment]
Sorry but no. I include add-ons that I find useful. Home Assistant allows multiple add-on repositories, so hopefully there's someone else who's done this or you can do it yourself.
