### ISSUE TITLE
[Request] Make sabnzbd link available in Sidebar with its icon

### ISSUE THREAD

**Issue by skycryer** [evilmarty/hassio-addons#6]
Make sabnzbd available in sidebar like zwave, esphome and other so it can be reached easily.

**Comment by evilmarty** [comment]
In order to make that happen it has to work via the supervisor's ingress controller, which is currently unsupported.

**Comment by evilmarty** [comment]
This has been implemented.

**Comment by MACscr** [comment]
I thought you said it was implemented, but its not showing ingress support, but I am not seeing that and I literally just installed it today. Am i missing something?

**Comment by evilmarty** [comment]
It did support ingress but it was reverted because it was very problematic, mainly with other integrations. At this stage it to reintroduce it would require patching SABznbd and I want to avoid that.
